<a href="https://colab.research.google.com/github/lemmedev/learning_ml/blob/master/Copy_of_data_preprocessing_tools_Learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Data.csv') # this code uses the read_csv() function from the pandas library to load data from a file named 'Data.csv' into a pandas DataFrame. The resulting DataFrame is then assigned to the variable
X = dataset.iloc[:, :-1] # Matrix of features or Independent variable
Y = dataset.iloc[:, -1] # Dependent variable vector



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
print(X)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0


In [ ]:
print(Y)

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


## Taking care of missing data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') # taking the mean and replacing the nan value.
imputer.fit(X.iloc[:, 1:3]) # In which columns do we want to replace the values. Here it is first and second. It connects imputer to matrix of features
X.iloc[:, 1:3] = imputer.transform(X.iloc[:, 1:3]) # it returns a new updated version of matrix of features of X with replacement from Missing salary and missing age columns.
# Hence we update the matrix of features of X.

In [ ]:
print(X)

   Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000


## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0] )], remainder = 'passthrough')
'''The highlighted code initializes a ColumnTransformer object named ct.
This object is part of scikit-learn's compose module and is used to apply different transformations
to different columns of your dataset. Let's break down its
components: - transformers=[('encoder', OneHotEncoder(), [0])]: This is a list of tuples,
where each tuple defines a transformation. Here, we have one transformation: - 'encoder': This is a
custom name for this specific transformation step. - OneHotEncoder(): This is the transformer itself.
OneHotEncoder converts categorical features (like 'Country' in your X dataframe) into a one-hot
numerical array. For example, if you have 'France', 'Spain', 'Germany', it will create three new
columns, one for each country, with 1 indicating presence and 0 indicating absence. - [0]: This
specifies that the OneHotEncoder should be applied to the column at index 0 of your input data X,
which is currently the 'Country' column. - remainder='passthrough': This argument specifies what
should happen to the columns that are not explicitly mentioned in the transformers list. 'passthrough'
means that any other columns (like 'Age' and 'Salary' in your X dataframe) will be kept in the output
without any modification.'''

X = np.array(ct.fit_transform(X))


In [ ]:
print(X)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 2.70000000e+01
  4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 5.00000000e+01
  8.30000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  6.70000000e+04]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [ ]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
# feature scaling is applied after the splitting of the dataset because applying feature scaling on the original
# array before the split would cost some info leakage on the test set. We would grab some info from the testset
# which we are not supposed to get because the testset is supposed to be new data with new observation.
# In crux: The essential reason why we should not apply feature scaling before the split it to prevent info
# info leakage on the testset which we are not supposed to have until the training is done.
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)


In [ ]:
print(X_train)

[[0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 2.70000000e+01
  4.80000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 5.00000000e+01
  8.30000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]]


In [ ]:
print(X_test)

[[0.0e+00 1.0e+00 0.0e+00 3.0e+01 5.4e+04]
 [1.0e+00 0.0e+00 0.0e+00 3.7e+01 6.7e+04]]


In [ ]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(Y_test)

[0 1]


## Feature Scaling

In [ ]:
'''
Feature scaling is important for several reasons, especially in machine learning algorithms:

Preventing Domination by Larger Values: Many machine learning algorithms calculate the distance between data points (e.g., K-Nearest Neighbors, Support Vector Machines, K-Means Clustering). If one feature has a much larger range of values than others (e.g., salary vs. age), its magnitude might disproportionately influence the distance calculations, effectively making the other features seem less important. Feature scaling ensures that all features contribute proportionally to the distance metric.

Faster Convergence for Gradient-Based Optimizers: Algorithms that use gradient descent (like neural networks, logistic regression, and linear regression) converge much faster when the features are scaled. Without scaling, the cost function can have elongated contours, making the optimization path take many small steps, whereas scaled features lead to more spherical contours and a direct path to the minimum.

Regularization: In some regularization techniques (like L1 and L2 regularization), the penalty term is based on the magnitude of the coefficients. If features are not scaled, features with larger values might be penalized more heavily, leading to unfair regularization.

Assumptions of Algorithms: Some algorithms explicitly or implicitly assume that all features are on a similar scale. For example, Principal Component Analysis (PCA) is sensitive to the variance of features, and unscaled features can lead to misleading principal components.

In essence, feature scaling helps algorithms perform better, converge faster, and yield more reliable results by putting all features on a comparable scale.
'''


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# feature scaling should not cover dummy variable (like country in the Data.csv).
'''
feature scaling is important for several reasons, especially in machine learning algorithms:

Preventing Domination by Larger Values: Many machine learning algorithms calculate the distance between data points (e.g., K-Nearest Neighbors, Support Vector Machines, K-Means Clustering). If one feature has a much larger range of values than others (e.g., salary vs. age), its magnitude might disproportionately influence the distance calculations, effectively making the other features seem less important. Feature scaling ensures that all features contribute proportionally to the distance metric.

Faster Convergence for Gradient-Based Optimizers: Algorithms that use gradient descent (like neural networks, logistic regression, and linear regression) converge much faster when the features are scaled. Without scaling, the cost function can have elongated contours, making the optimization path take many small steps, whereas scaled features lead to more spherical contours and a direct path to the minimum.

Regularization: In some regularization techniques (like L1 and L2 regularization), the penalty term is based on the magnitude of the coefficients. If features are not scaled, features with larger values might be penalized more heavily, leading to unfair regularization.

Assumptions of Algorithms: Some algorithms explicitly or implicitly assume that all features are on a similar scale. For example, Principal Component Analysis (PCA) is sensitive to the variance of features, and unscaled features can lead to misleading principal components.

In essence, feature scaling helps algorithms perform better, converge faster, and yield more reliable results by putting all features on a comparable scale.


why feature scaling should not cover dummy variable
You're right to ask that! Feature scaling should generally not be applied to dummy variables for a few key reasons:

Loss of Interpretability: Dummy variables (created by one-hot encoding) are inherently categorical and binary, representing the presence (1) or absence (0) of a particular category. Applying scaling (like standardization or normalization) would transform these 0s and 1s into other numerical values, destroying their clear, distinct meaning and making them harder to interpret as categorical indicators.

No Benefit to Algorithms: The purpose of scaling is often to equalize the influence of features with different magnitudes or to aid gradient-based optimization. Dummy variables, by their nature, already have a very limited and consistent range (0 or 1). Scaling them won't typically provide any additional benefit to algorithms; in fact, it can sometimes introduce complexity without improving performance.

Preserving Sparsity: If you have many categorical features, one-hot encoding can lead to a sparse matrix (mostly zeros). Scaling can convert these zeros into non-zero values, destroying the sparsity and potentially increasing computational burden without a corresponding gain.

In summary, dummy variables are already on a 'scale' that is optimal for representing their categorical nature. Applying further scaling would not enhance their utility and could even diminish their clarity and effectiveness in machine learning models.
'''

X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])




In [ ]:
print(X_train)

[[ 0.          0.          1.         -0.19159184 -1.07812594]
 [ 0.          1.          0.         -0.01411729 -0.07013168]
 [ 1.          0.          0.          0.56670851  0.63356243]
 [ 0.          0.          1.         -0.30453019 -0.30786617]
 [ 0.          0.          1.         -1.90180114 -1.42046362]
 [ 1.          0.          0.          1.14753431  1.23265336]
 [ 0.          1.          0.          1.43794721  1.57499104]
 [ 1.          0.          0.         -0.74014954 -0.56461943]]


In [ ]:
print(X_test)

[[ 0.          1.          0.         -1.46618179 -0.9069571 ]
 [ 1.          0.          0.         -0.44973664  0.20564034]]
